// <auto-generated />
using HotPinkWheels.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HotPinkWheels.Migrations
{
    [DbContext(typeof(ShopContext))]
    partial class ShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("HotPinkWheels.Models.Car", b =>
                {
                    b.Property<int>("CarID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("APK");

                    b.Property<int>("AmountofDoors");

                    b.Property<int>("AmountofPreviousOwners");

                    b.Property<int>("AmountofSeats");

                    b.Property<string>("Brand");

                    b.Property<string>("Color");

                    b.Property<string>("Enginetype");

                    b.Property<string>("Fueltype");

                    b.Property<int>("Fuelusage");

                    b.Property<int>("Horsepower");

                    b.Property<string>("Image");

                    b.Property<int>("ManufactureYear");

                    b.Property<int>("Mileage");

                    b.Property<string>("Model");

                    b.Property<int>("Price");

                    b.Property<int>("Topspeed");

                    b.Property<string>("Transmission");

                    b.Property<DateTime>("Warranty");

                    b.Property<int>("Weight");

                    b.HasKey("CarID");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
